name: invoice-extractor
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.10
  - numpy=1.26.0
  - pandas=2.2.2  # Saderīgs ar google-colab
  
  # ML
  - pytorch=2.7.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  
  # OCR
  - pdf2image=1.17.0
  - pytesseract=0.3.13
  - opencv-python=4.8.0.74  # Pieejamā versija
  
  # NLP
  - spacy=3.8.5
  - transformers=4.51.3
  
  # Utils
  - rich=13.7.1  # Saderīgs ar bigframes
  - pip=23.3.1
  - pip:
      - pdfplumber==0.11.0
      - langdetect==1.0.9